# Generated by Django 6.1.1 on 2026-09-27 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_type",
                    models.CharField(
                        choices=[("IN", "Stock In"), ("OUT", "Stock Out")], max_length=3
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_logs",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
