# Generated by Django 6.1.1 on 2026-09-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("product_code", models.CharField(max_length=50, unique=True)),
                ("hsn_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "gst_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("purchase_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("mrp", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("current_stock", models.PositiveIntegerField(default=0)),
                ("low_stock_limit", models.PositiveIntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
